apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name }}-deployment2
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: predictApp3
  template:
    metadata:
      labels:
        app: predictApp3
    spec:
      containers:
      - name: predict-container3
        image: s410071012/node3_predict:{{ .Values.deployment.image.tag }}
        command: ["/bin/sh"]
        args: ["-c", "while true; do python3 /home/jovyan/predict-code/inference.py;sleep 10;done"]
        ports: 
          - containerPort: 4300
        imagePullPolicy: Always

